import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_components/layout/sidebar";
import { Toaster } from "./_components/ui/sonner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});

export const metadata: Metadata = {
  title: "Stockly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full">
          <Sidebar />
          {children}
        </div>

        <Toaster />
      </body>
    </html>
  );
}
